/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  transpilePackages: [
    '@nextui-org/react',
    '@react-aria/visually-hidden',
    '@react-aria/utils',
    '@react-aria/interactions',
    '@react-stately/visually-hidden',
    '@nextui-org/system',
    '@nextui-org/theme',
    '@nextui-org/accordion',
    '@nextui-org/button',
    '@nextui-org/dropdown',
    '@nextui-org/modal',
    '@nextui-org/navbar',
    '@nextui-org/input',
    '@nextui-org/card',
    '@nextui-org/checkbox',
    '@nextui-org/link',
    '@nextui-org/tabs',
    '@nextui-org/ripple',
    '@nextui-org/switch',
    '@nextui-org/spinner',
    '@nextui-org/tooltip',
    '@nextui-org/avatar',
    '@nextui-org/popover',
    '@nextui-org/select',
    '@nextui-org/table',
    '@nextui-org/skeleton',
    '@nextui-org/divider',
    '@nextui-org/progress',
    '@nextui-org/radio',
    '@nextui-org/scroll-shadow',
    '@nextui-org/snippet',
    '@nextui-org/spacer',
    '@nextui-org/switch',
    '@nextui-org/use-aria-toggle',
    '@nextui-org/use-aria-button',
    '@nextui-org/use-disclosure',
    '@nextui-org/use-drip',
    '@nextui-org/use-aria-multiselect',
    '@nextui-org/use-aria-accordion',
    '@nextui-org/use-aria-button',
    '@nextui-org/use-aria-checkbox',
    '@nextui-org/use-aria-dialog',
    '@nextui-org/use-aria-dropdown',
    '@nextui-org/use-aria-menu',
    '@nextui-org/use-aria-modal',
    '@nextui-org/use-aria-overlays',
    '@nextui-org/use-aria-tabs',
    '@nextui-org/use-aria-tooltip',
    '@nextui-org/use-callback-ref',
    '@nextui-org/use-controllable-state',
    '@nextui-org/use-drag-and-drop',
    '@nextui-org/use-is-mobile',
    '@nextui-org/use-is-mounted',
    '@nextui-org/use-is-scrolling',
    '@nextui-org/use-merge-refs',
    '@nextui-org/use-on-click-outside',
    '@nextui-org/use-overlay-position',
    '@nextui-org/use-pagination',
    '@nextui-org/use-resize-observer',
    '@nextui-org/use-scroll-position',
    '@nextui-org/use-shortcut',
    '@nextui-org/use-update-effect',
    '@nextui-org/use-aria-button'
  ],
  images: {
    domains: ['res.cloudinary.com', 'via.placeholder.com'],
  },
  // Server Actions are enabled by default in Next.js 14+
  async rewrites() {
    return [
      {
        source: '/api/:path*',
        destination: 'https://sologix-web-nvm3.vercel.app/api/:path*',
      },
    ];
  },
};

module.exports = nextConfig;
